{% set name = "proplot" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bee013f524bde201c346b2b071ca784c151edc08a835b674c2e16ca43b7ccbd2

build:
  noarch: python
  number: 1 
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - matplotlib-base 
    - setuptools

test:
  imports:
    - proplot

about:
  home: https://proplot.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A comprehensive, easy-to-use matplotlib wrapper for making beautiful, publication-quality graphics.
  dev_url: https://github.com/lukelbd/proplot

extra:
  recipe-maintainers:
    - hmaarrfk
    - lukelbd
